use_weighted_dist: true
position_dim: 2
K: 2500.0 #2500.0
B: 20.0 #20
escape_factor: 150.0 #150.0
active_guide:
  execution_time: 10.0
  Kf: 300.0 # 100
  Bf: 5.0 # 0.1
  n_samples_filter: 10 #100
  phase_dot_th: 0.02 #0.05
  r_th: 0.02
  pre_auto_th: 0.3
  fade_gain: 10.0 #10.0
second_order:
  inertia: 0.1
  Kr: 100.0

